name: "Azure Static Website"
description: "Deploy files to Azure Blob Storage Container using a connection string"
inputs:
  connection-string:
    description: "Connection String of the Azure Storage Container"
    required: true
  folder:
    description: "Folder containing the files to be uploaded to the Storage Container"
    required: false
    default: "."
  blob-container-name:
    description: "Name of the Blob Container Storage"
    required: false
  public-access-policy:
    description: "Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value."
    required: false
  enabled-static-website:
    description: "Enabled static website"
    required: false
  index-file:
    description: "Index file for the static website"
    required: false
  error-file:
    description: "404 Error file for the static website"
    required: false
  remove-existing-files:
    description: "If the existing files should be removed before uploading the new files"
    required: false
  remove-files-listfile:
    description: "If remove-existing-files is false then pass list of file name to be deleted in deletefile.txt as param"
    required: false

branding:
  icon: "upload-cloud"
  color: blue
runs:
  using: "node12"
  main: "lib/index.js"
